version: '3.2'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "${WORDPRESS_PORT}:80"
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file: .env
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
volumes:
  mysql-volume:
